# Generated by Django 5.1.2 on 2024-10-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('entidade', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('telefone_fixo', models.CharField(max_length=20)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.estado')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipio')),
            ],
        ),
    ]
