# Generated by Django 5.1.2 on 2024-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='contato',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
