# Generated by Django 5.1.2 on 2024-10-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_contato_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='entidade',
        ),
        migrations.AddField(
            model_name='contato',
            name='interesse',
            field=models.CharField(blank=True, choices=[('Administracao', 'Administração'), ('AssistenciaSocial', 'Assistência Social'), ('ControleInterno', 'Controle Interno'), ('Cultura', 'Cultura'), ('DefesaCivil', 'Defesa Civil'), ('Educacao', 'Educação'), ('Financas', 'Finanças'), ('Inovacao', 'Inovação'), ('Juventude', 'Juventude'), ('LGBT', 'LGBT'), ('LimpezaUrbana', 'Limpeza Urbana e Manejo de Resíduos'), ('MeioAmbiente', 'Meio Ambiente'), ('MobilidadeUrbana', 'Mobilidade Urbana'), ('Planejamento', 'Planejamento e Desenvolvimento Urbano'), ('PPPConcessoes', 'PPPs e Concessões'), ('Previdencia', 'Previdência Estaduais e Municipais'), ('ProcuradoresGerais', 'Procuradores Gerais'), ('ProtecaoDados', 'Proteção de Dados Pessoais dos Municípios'), ('RelacoesInternacionais', 'Relações Internacionais'), ('Saneamento', 'Saneamento'), ('Saude', 'Saúde'), ('SegurancaPublica', 'Segurança Pública'), ('Turismo', 'Turismo')], max_length=255),
        ),
    ]
