# Generated by Django 5.1.2 on 2024-10-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_contato_entidade_contato_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='interesse',
        ),
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
