# Generated by Django 5.1.2 on 2024-10-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_contato_interesse_alter_contato_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.estado'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipio'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone_fixo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='contato',
            name='interesses',
            field=models.ManyToManyField(blank=True, to='base.interesse'),
        ),
    ]
