# Generated by Django 5.1.2 on 2024-10-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_interesse_alter_contato_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='interesses',
        ),
        migrations.DeleteModel(
            name='Interesse',
        ),
    ]
