# Generated by Django 5.1.2 on 2024-10-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_contato_estado_alter_contato_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.estado'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipio'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone_fixo',
            field=models.CharField(default='Desconhecido', max_length=20),
            preserve_default=False,
        ),
    ]
