# Generated by Django 5.1.2 on 2024-10-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_contato_estado_alter_contato_municipio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='interesses',
            field=models.ManyToManyField(blank=True, to='base.interesse'),
        ),
    ]
