# Generated by Django 5.1.2 on 2024-10-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_contato_celular_email_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='endereco',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='telefone',
        ),
    ]
