# Generated by Django 4.2.16 on 2024-10-25 18:52

from django.db import migrations, models
import django.db.models.deletion
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_contato_celular_remove_contato_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='emails',
            field=multi_email_field.fields.MultiEmailField(default=[]),
        ),
        migrations.AlterField(
            model_name='email',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailss', to='base.contato'),
        ),
    ]
