# Generated by Django 4.2.16 on 2024-10-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_contact_telephone_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='emails',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Telephone',
        ),
    ]
