# Generated by Django 4.2.16 on 2024-11-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_telephone_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='contato',
            new_name='contact',
        ),
    ]
