# Generated by Django 4.2.16 on 2024-11-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_cargo_alter_contato_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
