# Generated by Django 4.2.16 on 2024-11-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_contato_cargo_delete_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cargo'),
        ),
    ]
